// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['protocols']['ConnectionManager']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['protocols']['ConnectionManager']['Disconnect'](arg1);
}
