// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Connect(arg1:types.ConnectionInput):Promise<types.ConnectResult>;

export function Disconnect(arg1:string):Promise<boolean>;
